apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: cast
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  
  # 用于生成票据的密钥
  TICKET_SECRET_KEY: "your-secure-secret-key-for-hmac" 