apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 命名空间
  - namespace.yaml
  
  # ConfigMap 和 Secret
  - configmaps/app-config.yaml
  - secrets/app-secrets.yaml
  
  # 基础设施组件
  - statefulsets/postgres.yaml
  - services/postgres.yaml
  - statefulsets/redis.yaml
  - services/redis.yaml
  - statefulsets/zookeeper.yaml
  - services/zookeeper.yaml
  - statefulsets/kafka.yaml
  - services/kafka.yaml
  
  # 应用组件
  - deployments/main-service.yaml
  - services/main-service.yaml
  - deployments/ticket-generator.yaml
  - services/ticket-generator.yaml
  - deployments/vote-consumer.yaml
  
  # 入口
  - ingress/cast-ingress.yaml 