apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-generator
  namespace: cast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-generator
  template:
    metadata:
      labels:
        app: ticket-generator
    spec:
      containers:
      - name: ticket-generator
        image: cast:latest
        imagePullPolicy: IfNotPresent
        command: ["uvicorn", "app.workers.ticket_generator:app", "--host", "0.0.0.0", "--port", "8001"]
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.3" 