apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: little-vote
spec:
  selector:
    app: kafka
  ports:
  - name: client
    port: 9092    # 集群内访问端口
    targetPort: 9092
  clusterIP: None 